torso_controller:
  type: position_controllers/JointTrajectoryController
#  type: effort_controllers/JointTrajectoryController
  joints:
     - torso_revolution_joint
     - torso_elevation_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains: # for effort controller
    torso_revolution_joint: {p: 100.0, i: 0.01, d: 10.0}
    torso_elevation_joint: {p: 100.0, i: 0.01, d: 10.0}

pantilt_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - torso_pantilt_pan_joint
     - torso_pantilt_tilt_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
