torso_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - torso_revolution_joint
     - torso_elevation_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

#  elevation_controller:
#      type: effort_controllers/JointPositionController
#      joint: elevation_joint
#      pid: {p: 1000.0, i: 0.01, d: 100.0}
#  
#  revolution_controller:
#      type: effort_controllers/JointPositionController
#      joint: revolution_joint
#      pid: {p: 1000.0, i: 0.01, d: 100.0}
